PIC EQU 20H
INT0 EQU 24H
PA EQU 30H
PB EQU 31H
CA EQU 32H
CB EQU 33H

ORG 40
IDF10 DW GESTOR

ORG 1000H
MSJ DB "PRESIONE F10 PARA COMENZAR"
MSJ2 DW ?

ORG 3400H
CONF_PIO:PUSH AX
         MOV AL, 11111101B
         OUT CA,AL
         MOV AL,0
         OUT CB,AL
         POP AX
         RET

ORG 3800H
GESTOR:PUSH AX
      MOV DL,1
      MOV AL, 20H
      OUT PIC,AL
      POP AX
      IRET

ORG 3000H
IMPRIMIR:PUSH BX
      PUSH AX
      MOV BX,SP
      ADD BX,6
      MOV BX,[BX]
      CALL CONF_PIO
      MOV AH,10
POLL: IN AL,PA; CONSULTO SI ESTÁ LIBRE
      AND AL,1
      JNZ POLL
      MOV AL,[BX];IMPRIMO CHAR
      OUT PB,AL
      INC BX
      DEC AH
      MOV AL, PA;STROBE 1
      OR AL,2
      OUT PA,AL
      MOV AL, PA;STROBE 0
      AND AL,11111101B
      OUT PA,AL
      CMP AH,0
      JNZ POLL
      POP AX
      POP BX
      RET
      
ORG 2000H
CLI
MOV AL,11111110B
OUT PIC+1,AL
MOV AL,10
OUT INT0,AL
MOV BX, OFFSET MSJ
MOV AL, OFFSET MSJ2 - OFFSET MSJ
MOV DL,0
STI
INT 7
MOV BX, OFFSET MSJ2
MOV AH,10

BUCLE:CMP DL,1
JNZ BUCLE
LAZO:CMP AH,0
     JZ EMPIEZO
     INT 6
     DEC AH
     INC BX
     JMP LAZO
EMPIEZO:MOV BX, OFFSET MSJ2
      PUSH BX
      CALL IMPRIMIR
      POP BX
FIN:  HLT
      END
